"""Shared test emails for model evaluation."""

# flake8: noqa
test_emails = [
    "Congratulations! You won $1000 free cash prize. Click here now to claim!!!",
    "Hi John, please find attached the meeting notes from yesterday's call.",
    "URGENT: Your account has been suspended. Verify now at http://scam-site.com",
    "Can we reschedule tomorrow's lunch to 1pm instead?",
    "Buy cheap v1agra 100% free shipping limited offer act now!!!",
    "For your Assignment 1, word count of 3100 is already slightly too high. If you still want to add more content, you may need to remove some existing content.It depends on how you present your ideas and how much those ideas are 'borrowed' from various sources. I suggest you provide citations to those sources that have strong influence on your ideas.For Assignment 2A, you can assume that all edges in the map have positive weight. Hence, there is no need to worry about negative weight. Using another language for GUI (I supposed you are referring to using game engine + scripting) is allowed as long it can be invoked directly from your main program and does not require complex setup. Make sure you explain clearly how to execute your program in the report.",
    "Please be reminded that the Assignment 1 report is due this Sunday (17th May). No further extension is allowed (except under special circumstances) as the submission deadline has been extended due to Canvas disruption. Note that you need to adhere to the word count (2500 - 3000 words). Report that is too long or too short will be penalised.Report that is slightly above or below the limit (within 10%) is accepted without penaltyEach picture/diagram is equivalent to 50 words.Submit early so that if the Turnitin similarity score is too high (>24%), you still have time to improve it. Turnitin similarity score of 25% - 40% is subjected to penalty and if the score is higher than 40%, a plagiarism hearing might be required.",
    "Show, Last weekend, I was sick and couldn't do much of anything. So I used Claude Code to build a simple game. Think Frogger meets Space Invaders (it was actually pretty fun... DM me if you want to check it out).Of course, I expected the usual issues, like bugs and rough edges — but this wasn't the biggest development hurdle. The code was often correct. The problem was drift.Before I explain how I tackled this challenge: here's your reminder that AI April is nearly over. There's only few days left to take advantage of our best discount of the year:",
    "Supporters can now pay you in USDC, and the money lands in your account in your local currency. Same payouts, same dashboard, nothing new for you to learn.It's already on for your page. Next time a supporter wants to pay this way, they can.Many thanks,Buy Me a Coffee Team PS: If you're on Stripe Standard, you'll need to enable this from your settings before your supporters can pay with USDC.",
    "This email was sent to: SHOWWAIYAN555@GMAIL.COM You have received this email because you are a Maybank customer. To avoid future emails from Maybank being automatically sent to your junk mail folder, we suggest that you add our email address m2u@maybank.com.my to your Address Book and/or the Approved Sender list.DisclaimerYou are advised not to send any confidential and/or important information to the Bank via e-mailThe Personal Data Protection Act 2010 has been enforced on 15 December 2013. Please read our Privacy Notice which can be found at https://www.maybank.com/en/privacy-statement.page or at any branch for details on how we process/protect your personal data.This email and any of its attachments are confidential and may also be privileged. If you are not the intended recipient, please disregard the email and delete it immediately. Do not disclose, copy, circulate or in any other way, use or rely on the information contained in this email or its attachments. Email are not guaranteed to be secure or error-free as the message and any of its content could be intercepted, corrupted, lost, delayed, incomplete and amended. Please do not reply to this email.If you do not wish to receive any promotional information from Maybank via email, unsubscribe here.",
    """\nPayment Success for [ 26052270538 ]\nInbox\n\nFiuu <notification@fiuu.com>\nFri, May 22, 2:11\u200fPM (1 day ago)\nto me\n\nMerchant Logo\tPayment successful\nMYR 12.20\nPAYMENT DETAILS\nTransaction ID\t3722933396\nEmail\tau****@gmail.com\nContact No.\t10***6487\nService Items\tZUS Coffee billing\nPayment Method\tCredit/Debit Card\nOrder Number\t26052270538\nName of Cardholder\tAun***********hu\nAuthorized Date/Time\t2026-05-22 14:10:55\nApproval code\t154170\nsupport support@fiuu.com\t\nPowered by   fiuu\n""",
]
